### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by simonc** [mongoid/mongoid-rspec#43]
Hi,

I'm working on  a Rails 3.1 application with mongoid (2.0.2) and rspec (2.6.0).

I added gem 'mongoid-rspec' to my Gemfile and added the configuration file in spec/support.

My model is the following :

``` ruby
class Folder
  include Mongoid::Document
  ...
  has_many :documents
end
```

and my test is the following :

``` ruby
describe Folder do
  it { should have_many(:documents) }
end
```

I checked that the spec_helper.rb requires the files in support.
When I launch my test, it tells me this:

```
undefined method `has_many?' for #<Folder:0x00000101461250>
```

Did I miss something ?

Thanks
